from datetime import datetime
from typing import Protocol

from knowledge.models import Claim, Source


class KnowledgePort(Protocol):
    """Knowledge persistence port.

    PostgreSQL implementations (``PgKnowledge``) are constructed with a
    ``knowledge_base_id`` so every query is scoped to one knowledge base.
    In-memory implementations do not require a knowledge base id (Task 5).
    """

    def save_source(self, source: Source) -> Source: ...
    def get_source(self, source_id: str) -> Source | None: ...
    def list_sources(self) -> list[Source]: ...
    def save_source_text(self, source_id: str, text: str) -> None: ...
    def get_source_text(self, source_id: str) -> str | None: ...
    def append_claim(self, claim: Claim) -> Claim: ...
    def get_claim(self, claim_id: str) -> Claim | None: ...
    def get_active_claims(self, subject: str, predicate: str | None = None) -> list[Claim]: ...
    def get_claim_history(self, claim_family_id: str) -> list[Claim]: ...
    def mark_superseded(self, claim_id: str, valid_to: datetime | None = None) -> None: ...
    def get_claims_for_source(self, source_id: str) -> list[Claim]: ...
    def get_claims_by_status(self, status: str) -> list[Claim]: ...
    def as_of(self, query_time: datetime, family_id: str) -> Claim | None: ...
    def add_quarantine(self, reason: str, raw: dict) -> None: ...
    def list_quarantine(self) -> list[dict]: ...
