from typing import Protocol

from knowledge.models import Claim, Source


class KnowledgePort(Protocol):
    def save_source(self, source: Source) -> Source: ...
    def get_source(self, source_id: str) -> Source | None: ...
    def save_source_text(self, source_id: str, text: str) -> None: ...
    def get_source_text(self, source_id: str) -> str | None: ...
    def append_claim(self, claim: Claim) -> Claim: ...
    def get_claim(self, claim_id: str) -> Claim | None: ...
    def get_active_claims(self, subject: str, predicate: str | None = None) -> list[Claim]: ...
    def get_claim_history(self, claim_family_id: str) -> list[Claim]: ...
    def add_quarantine(self, reason: str, raw: dict) -> None: ...
    def list_quarantine(self) -> list[dict]: ...
