from typing import Protocol


class OntologyPort(Protocol):
    def resolve_entity_type(self, mention: str) -> str | None: ...
    def allowed_predicates(self, subject_type: str, object_type: str) -> list[str]: ...
    def normalize_term(self, raw: str) -> str: ...
    def validate_claim(self, subject_type: str, predicate: str, object_type: str) -> bool: ...
    def register_entity(self, mention: str, entity_type: str) -> None: ...
    def register_predicate(self, subject_type: str, predicate: str, object_type: str) -> None: ...
    def register_alias(self, alias: str, canonical: str) -> None: ...
