from datetime import datetime
from typing import Protocol

from knowledge.models import Claim, Event, Source, SourceChunk, TopicCluster


class KnowledgePort(Protocol):
    """Knowledge persistence port.

    PostgreSQL implementations (``PgKnowledge``) are constructed with a
    ``knowledge_base_id`` so every query is scoped to one knowledge base.
    In-memory implementations do not require a knowledge base id (Task 5).
    """

    def save_source(self, source: Source) -> Source: ...
    def get_source(self, source_id: str) -> Source | None: ...
    def list_sources(self) -> list[Source]: ...
    def delete_source(self, source_id: str) -> None: ...
    def update_source_status(self, source_id: str, status: str) -> None: ...
    def save_source_text(self, source_id: str, text: str) -> None: ...
    def get_source_text(self, source_id: str) -> str | None: ...
    def append_claim(self, claim: Claim) -> Claim: ...
    def get_claim(self, claim_id: str) -> Claim | None: ...
    def get_active_claims(self, subject: str, predicate: str | None = None) -> list[Claim]: ...
    def get_claim_history(self, claim_family_id: str) -> list[Claim]: ...
    def mark_superseded(self, claim_id: str, valid_to: datetime | None = None) -> None: ...
    def get_claims_for_source(self, source_id: str) -> list[Claim]: ...
    def get_claims_by_status(self, status: str) -> list[Claim]: ...
    def as_of(self, query_time: datetime, family_id: str) -> Claim | None: ...
    def add_quarantine(self, reason: str, raw: dict) -> None: ...
    def list_quarantine(self) -> list[dict]: ...
    def approve_quarantine(self, quarantine_id: int) -> Claim: ...
    def append_event(self, event: Event) -> Event: ...
    def list_events(self, source_id: str | None = None) -> list[Event]: ...
    def save_chunks(self, source_id: str, chunks: list[SourceChunk]) -> None: ...
    def list_chunks(self, source_id: str, *, status: str = "active") -> list[SourceChunk]: ...
    def get_chunk(self, chunk_id: str) -> SourceChunk | None: ...
    def mark_chunks_stale(self, source_id: str) -> None: ...
    def purge_stale_chunks(self, source_id: str) -> int: ...
    def update_chunk(self, chunk: SourceChunk) -> SourceChunk: ...
    def save_topic_clusters(self, clusters: list[TopicCluster]) -> None: ...
    def list_topic_clusters(self, *, status: str = "active") -> list[TopicCluster]: ...
    def get_topic_cluster(self, cluster_id: str) -> TopicCluster | None: ...
    def mark_topic_clusters_stale(self) -> None: ...
